### ISSUE TITLE
How can i use this component on mobile devices

### ISSUE THREAD

**Issue by mrTangYun** [ankeetmaini/react-infinite-scroll-component#10]
How can i use this component on mobile devices? When I use this component I can't scroll any element on the phone browsers

**Comment by ankeetmaini** [comment]
Hey, it should work seamlessly on mobile devices too! If not this is a bug, I'll check this today!

**Comment by ankeetmaini** [comment]
Hey just a quick update on the issue. I found out some problems while testing on the mobile devices. viewport was missing in the demo page. I tested the demo page on Android chrome browser and it works.

Can you also check now? I'll test this on iOS device and update this issue

**Comment by mrTangYun** [comment]
I test the demo page:
http://ankeetmaini.github.io/react-infinite-scroll-component/ on the ios
(safari and chrome), it's not working yet。
the 'refreshFunction' is work fine, but i can't scroll the page down to
show more data。

2017-03-03 15:25 GMT+08:00 Ankeet Maini <notifications@github.com>:

**Comment by pinturic** [comment]
I am using the component on mobile in a cordova project and I am not having any issue

**Comment by ankeetmaini** [comment]
Need help to debug the issue.

**Comment by mrTangYun** [comment]
Hey, what' s can i do for you ?

2017-03-07 14:34 GMT+08:00 Ankeet Maini <notifications@github.com>:

**Comment by ankeetmaini** [comment]
Can you debug in the device where it doesn't scroll, I tried to debug using chrome devtools mobile simulator, as well as on my Android Chrome browser. It scrolls.

Basically anything which tracks that issue down 😄

**Comment by mrTangYun** [comment]
My pleasure， I debug using chrome devtools mobile simulator,  it's work too.
but on my Android device(Nexus 5 Chrome browser), I record a video
http://youtu.be/gDiSMx3NxWk.

2017-03-07 14:42 GMT+08:00 Ankeet Maini <notifications@github.com>:

**Comment by ankeetmaini** [comment]
Oh shit, it's real bad on your phone! Let me debug, why is that even happening, it shouldn't :(

**Comment by mrTangYun** [comment]
:)  that's Android.  and this' s Iphone https://youtu.be/N5F5KYVzWGk
<https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxcheckurl?requrl=https%3A%2F%2Fyoutu.be%2FN5F5KYVzWGk&skey=%40crypt_93b593b0_d4579d133bdee955b10c23e7c9c77646&deviceid=e277253728374709&pass_ticket=r4zh0KuM0Wa2Ak8pbS5B7LS6j6JwI%252BAdQklPgMLCV3lj7eA%252B8Te09pZNyFlz%252BBiU&opcode=2&scene=1&username=@c67d4ba171241d900e8c4f41f4969774>.
thanks for your work

2017-03-07 15:07 GMT+08:00 Ankeet Maini <notifications@github.com>:

**Comment by ankeetmaini** [comment]
@mrTangYun Hey, I've fixed it, can you try this again. Thanks a lot!

**Comment by mrTangYun** [comment]
Yes, it' s work, you fixed it. Congratulations and Thank you
