### ISSUE TITLE
pullDownToRefresh not working when hasMore is false

### ISSUE THREAD

**Issue by haresh0398** [ankeetmaini/react-infinite-scroll-component#107]
when all the documents are fetched, the state is updated to hasMore false 
But when new documents are added and the user tries to refresh. the pullDownToRefresh not working since hasMore is false. 
Refresh content should not depend on hasMore isn't?
hope you guys see this

**Comment by KuNman** [comment]
Up. Still bugged.

**Comment by DrobyshevAlex** [comment]
I have got the same issue, why that topic has been closed?

**Comment by DrobyshevAlex** [comment]
Property **actionTriggered** becomes **false** in [line 91](https://github.com/ankeetmaini/react-infinite-scroll-component/blob/master/app/index.js#L91)

But if server responses **empty array** [] then dataLength won't be changed.

[Line 86](https://github.com/ankeetmaini/react-infinite-scroll-component/blob/master/app/index.js#L86) doesn't allow set to **false** property **actionTriggered**.

I think  dataLength should not block refresh function.

**Comment by ankeetmaini** [comment]
I depend on DataLength to know if I should call the API again, it doesn't block render, new props passed in will automatically show up, like children

**Comment by strawberry3269** [comment]
I got the same issue
