### ISSUE TITLE
Does this component supports error handling?

### ISSUE THREAD

**Issue by riteshchandna** [ankeetmaini/react-infinite-scroll-component#109]
Let's say I am loading 6th page and the service returns some error (Gateway time out for example). Does this component have an option to display the error message and have a button to "Try again" ?

**Comment by ankeetmaini** [comment]
Currently, no. The `next` function prop you send does not expect to be a promise. Instead you can do something like

```jsx
<InfiniteScroll
  next={() => {
    fetchData().then(res => // set state here in success)
    .catch(err => { this.setState({error: err})}) // show a retry button dependent on this

  }}
>
  {data}
</InfiniteScroll>
{this.state.err && <button>API called failed, try again</button>}
```

Let me know if this doesn't solve your use case. Closing this, feel free to reopen with more details
