### ISSUE TITLE
Next function broken in v4.0.0

### ISSUE THREAD

**Issue by nero120** [ankeetmaini/react-infinite-scroll-component#111]
I upgraded from v3.0.2 to v4.5.2 and discovered that the `next` function fires only once. My code:

```
<InfiniteScroll
  datalength={ this.state.items.length }
  hasMore={ true }
  loader={<h4>Loading...</h4>}
  next={ this.fetchMoreData }
  scrollableTarget={ this.getScrollableContainer() }>
  { this.state.items }
</InfiniteScroll>
```

I've removed all `shouldComponentUpdate` functions in the component hierarchy (to make sure the components are always re-rendered) but still `next` only fires once when I scroll to the bottom of my `scrollableTarget`. Results are loaded and displayed, but when I scroll to the bottom of `scrollableTarget` again, `next` does not get triggered at all.

To try and discover the cause, I downgraded to v4.0.0 and found that the the issue remains, so it appears the issue was introduced in v4.0.0 as v3.0.2 works with the above code.

To remove `scrollableTarget` as a possibility of the cause, I switched out this prop for a `height` but the issue remains.

One thing I noticed, the first scroll `loader` appears and is appended beneath the items, but on the second scroll the loader is already present - symptom of the issue?

**Comment by ankeetmaini** [comment]
Is it broken in the latest version also? Latest is 4.5.2. Can you please
check and confirm?

**Comment by nero120** [comment]
It is yes, I originally updated to latest (4.5.2) which is when I discovered the issue. I later downgraded to 4.0.0 to find the first version the issue occurs in.

-------- Original Message --------

**Comment by oscar-corredor** [comment]
same problem here

**Comment by sspiff** [comment]
data**l**ength  =>  data**L**ength ?

**Comment by kierantaylor** [comment]
I've also had to downgrade to v3.0.2 to get this to work. v4 must have introduced the break. I haven't looked into it though,

**Comment by ankeetmaini** [comment]
dataLength was misspelled. Can you check again? I'm using 4.5.2 in
production. It seems to work fine though.

**Comment by nero120** [comment]
Yes that was it thanks @sspiff , my bad! 😄
