### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientHeight' of null

### ISSUE THREAD

**Issue by davidb1** [ankeetmaini/react-infinite-scroll-component#118]
Getting this when scrolling to the top most or bottom element on clientHeight evaluation:
```
key: "isElementAtBottom",
value: function isElementAtBottom(target) {
            var scrollThreshold = arguments.length <= 1 || arguments[1] === undefined ? 0.8 : arguments[1];
            var clientHeight = target === document.body || target === document.documentElement ? window.screen.availHeight : target.clientHeight;
```

Any idea why?

**Comment by ankeetmaini** [comment]
Can you give me a repro? A github repository or codesandbox link?

**Comment by davidb1** [comment]
Can't reproduce in a new repo and can't catch the error when debugging. Build might be changing code

**Comment by davidb1** [comment]
@ankeetmaini 
Still getting this, when would the target be null here?

`  onScrollListener = (event: MouseEvent) => {
    if (typeof this.props.onScroll === 'function') {
      // Execute this callback in next tick so that it does not affect the
      // functionality of the library.
      setTimeout(() => this.props.onScroll && this.props.onScroll(event), 0);
    }

    const **target** =
      this.props.height || this._scrollableNode
        ? (event.target as HTMLElement)
        : document.documentElement.scrollTop
        ? document.documentElement
        : document.body;

    // return immediately if the action has already been triggered,
    // prevents multiple triggers.
    if (this.actionTriggered) return;

    const atBottom = this.isElementAtBottom(target, this.props.scrollThreshold);

    // call the `next` function in the props to trigger the next data fetch
    if (atBottom && this.props.hasMore) {
      this.actionTriggered = true;
      this.setState({ showLoader: true });
      this.props.next && this.props.next();
    }

    this.lastScrollTop = target.scrollTop;
  };`

![image](https://user-images.githubusercontent.com/13868996/71360864-dad77a00-2599-11ea-8477-80991f75a071.png)

**Comment by mfreville** [comment]
I have this error too when I want scroll bottom with a fixed height on InfiniteScroll props.
