### ISSUE TITLE
Scroll up

### ISSUE THREAD

**Issue by fireflypie** [ankeetmaini/react-infinite-scroll-component#120]
Would be nice to have ability to scroll up. 
Eg. Facebook chat, where you scroll up to see your previous messages.

Any ideas on that or any Forks I could use?

**Comment by osmarpb97** [comment]
@joserivera12 and i made a pr to make this you can check in https://github.com/ankeetmaini/react-infinite-scroll-component/pull/207

**Comment by ankeetmaini** [comment]
This is now added in the latest version. Thanks to @osmarpb97
