### ISSUE TITLE
Function is triggered when scrolling up

### ISSUE THREAD

**Issue by YassienW** [ankeetmaini/react-infinite-scroll-component#125]
Is this intentional? It causes a lot of inconvenience and redundant calls.

[Live Example](https://codesandbox.io/s/react-infinite-scroll-example-0ve8e)

Try scrolling down to the end then scrolling up, it will fetch more data when scrolling up.

**Comment by rosbel** [comment]
@YassienW we're seeing a very similar issue. The issue for us occurs after pull to refresh, scrolling down will refetch data

**Comment by YassienW** [comment]
I don't think this is getting fixed. I ended up creating my own implementation, fairly straight forward.

**Comment by ankeetmaini** [comment]
This should be fixed in the latest version. Please reopen if it's still there.
