### ISSUE TITLE
componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by jaexplorer** [ankeetmaini/react-infinite-scroll-component#140]
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: InfiniteScroll

I get this warning in my console constantly. Am I using InfiniteScroll incorrectly or this legit something that needs to be addressed?

**Comment by edekk** [comment]
To overcome this issue browse 
`{your_project}\node_modules\react-infinite-scroll-component\lib\index.js`
and change:
`key: "componentWillReceiveProps",
	    value: function componentWillReceiveProps(props) {
	     ...
`
into:
`key: "componentDidUpdate",
	    value: function componentDidUpdate(props) {...`

Keep in mind you edit the build version, so for good measure you could also edit pre-build file 
(`{your_project}\node_modules\react-infinite-scroll-component\app\index.js`) and change function names there as well.

**Comment by Falkyouall** [comment]
this should be patched by the authors asap. the only other way i see here is to apply [npm patch-package](https://www.npmjs.com/package/patch-package). this will edit the wrong-ish npm module every time you type npm install, and therefore the only sustainable way to accomplish this besides waiting for a new release.

**Comment by ankeetmaini** [comment]
Will look into it this weekend. Sorry for the trouble

**Comment by Falkyouall** [comment]
@ankeetmaini thank you.

**Comment by ankeetmaini** [comment]
@Falkyouall latest release has this change? I see in master the method was renamed to "UNSAFE_ComponentWillReceiveProps". You shouldn't be getting any warnings.

**Comment by AmitNeuhaus** [comment]
Im still seeing this warning when using the official npm install package.
am i doing something wrong?

**Comment by NithinRauj** [comment]
> To overcome this issue browse
> `{your_project}\node_modules\react-infinite-scroll-component\lib\index.js`
> and change:
> `key: "componentWillReceiveProps", value: function componentWillReceiveProps(props) { ... `
> into:
> `key: "componentDidUpdate", value: function componentDidUpdate(props) {...`
> 
> Keep in mind you edit the build version, so for good measure you could also edit pre-build file
> (`{your_project}\node_modules\react-infinite-scroll-component\app\index.js`) and change function names there as well.

Hey @ankeetmaini  I am also getting the same warning message.So I tried doing this fix but I couldn't find a  lib folder in my node_modules.So how to fix this error ? By the way I also used the official npm package.

**Comment by akkisagiraju** [comment]
Using this in strict mode is resulting in a warning message.

`Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code.`

**Comment by tigerblue77** [comment]
Why close ? This issue is still present in strict mode... How to fix it ?

**Comment by ali-78** [comment]
It has trouble. It didn't fix. What should I do?

**Comment by Comediant24** [comment]
I agree! The problem is not solved!
