### ISSUE TITLE
How can I use this component to infinite scroll horizontally?

### ISSUE THREAD

**Issue by xNicklaj** [ankeetmaini/react-infinite-scroll-component#142]
So I have an horizontal list, but how do I make it work with InfiniteScroll horizontally?

**Comment by ankeetmaini** [comment]
As of the current implementation it can't work horizontally. I've to tweak
some things probably to make it work. Sorry about that!

**Comment by xNicklaj** [comment]
Oh okay, thanks anyways! in the end I've managed to build my own way to create an infinite scroller!

**Comment by mariomurrent-softwaresolutions** [comment]
> Oh okay, thanks anyways! in the end I've managed to build my own way to create an infinite scroller!

How did you do that?

**Comment by xNicklaj** [comment]
> > Oh okay, thanks anyways! in the end I've managed to build my own way to create an infinite scroller!
> 
> How did you do that?

I don't remember how I did that to be honest, it's too long ago. But I see that on NPM there are now modules for that!
https://www.npmjs.com/package/react-horizontal-infinite-scroll
