### ISSUE TITLE
import error with v.5.0.0

### ISSUE THREAD

**Issue by sT0pe** [ankeetmaini/react-infinite-scroll-component#148]
Error after update package to latest version

./node_modules/react-infinite-scroll-component/dist/index.mjs
Can't import the named export 'throttle' from non EcmaScript module (only default export is available)

**Comment by ankeetmaini** [comment]
Can you tell me the webpack version?

**Comment by ankeetmaini** [comment]
Or a sample repository where I can see this?

**Comment by ankeetmaini** [comment]
I just pushed a fix, removing .mjs module. Could you confirm if this is fixed? @sT0pe

**Comment by kvandake** [comment]
I get the same error.

packages.json
```json
"dependencies": {
  "next": "^9.1.2", 
  "react": "^16.11.0"
}
```

**Comment by sT0pe** [comment]
@ankeetmaini yes in v.5.0.1 error is fixed. Thanks

> Can you tell me the webpack version?
"name": "webpack",
"version": "4.39.0",
