### ISSUE TITLE
[Request] Changelog

### ISSUE THREAD

**Issue by emregency** [ankeetmaini/react-infinite-scroll-component#150]
When I see a jump from 4.5.3 to 5.0.1, I am scared when I do not find a changelog. Is it possible to have one?

**Comment by ankeetmaini** [comment]
I'm sorry, it was a port from JS to TS. No API changes. I'll add a changelog. Thanks.

**Comment by ankeetmaini** [comment]
I have now started publishing changelogs in Releases page. Thanks!

**Comment by emregency** [comment]
I saw that :) thanks! Great start.
