### ISSUE TITLE
Large screen

### ISSUE THREAD

**Issue by jcsistemas2001** [ankeetmaini/react-infinite-scroll-component#16]
Hi,

I just integrated the component in my application and seems work perfect.

When the screen is large enough to show all the items (for example, 10 items), there is not scroll bar. At that moment, the component don't work. 

Please, may I know your suggestion?

Thanks!

**Comment by ankeetmaini** [comment]
Hi, the easiest solution would be to fetch enough items so that scroll
appears. The way this works is by attaching an event listener onscroll. And
if there's no scroll it wouldn't know when to trigger the next call!

So instead of say 10 items can you show 20?

**Comment by jcsistemas2001** [comment]
Hi ankeetmaini, Thanks for your quick reply and suggestion. I applied 20 items for now. 
I was thinking a way to calculate this number according with client screen size. This will be on my side and is not related with the scroll.
