### ISSUE TITLE
`loader` prop is now required?

### ISSUE THREAD

**Issue by ipanasenko** [ankeetmaini/react-infinite-scroll-component#162]
As specified in types: https://github.com/ankeetmaini/react-infinite-scroll-component/blob/master/src/index.tsx#L10

Is `loader` prop required now or is it a typo in types?

**Comment by vladagurets** [comment]
Any updates?

**Comment by ankeetmaini** [comment]
This was done a long back so that the users can supply what they want to show while loading. Some text or custom spinner component.
