### ISSUE TITLE
Typescript definitions broken

### ISSUE THREAD

**Issue by emlynmac** [ankeetmaini/react-infinite-scroll-component#167]
Just attempted updating from 4.5.3 => 5.0.4 and it breaks with importing the package.

I'm using typescript 3.7.5
`import * as InfiniteScroll from "react-infinite-scroll-component";`
worked previously.

Now we get:
```
Failed to compile.
(125,12): JSX element type 'InfiniteScroll' does not have any construct or call signatures.
```

**Comment by ankeetmaini** [comment]
Directly importing like import InfiniteScroll from
"react-infinite-scroll-component";
works?

**Comment by emlynmac** [comment]
I tried that too, but also fails.

**Comment by shilangyu** [comment]
Can't reproduce it. Any steps that can be followed?

**Comment by bisu8018** [comment]
Do you even use "@types/react-infinite-scroll-component"?

**Comment by shilangyu** [comment]
There is no need, types are included with the package
