### ISSUE TITLE
React v15.5.0 Throws Deprecation Warnings

### ISSUE THREAD

**Issue by emilyrohrbough** [ankeetmaini/react-infinite-scroll-component#17]
> The biggest change is that we've extracted React.PropTypes and React.createClass into their own packages. Both are still accessible via the main React object, but using either will log a one-time deprecation warning to the console when in development mode

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by juank11memphis** [comment]
Having the same problem here...

**Comment by ankeetmaini** [comment]
Thank you so much for raising this issue. I'm out this week. Will fix this
once I'm back :-)
