### ISSUE TITLE
Warning: key is not a prop

### ISSUE THREAD

**Issue by groupsky** [ankeetmaini/react-infinite-scroll-component#177]
After upgrading I get the warning from react about using a [special prop](https://reactjs.org/warnings/special-props.html):

```
      Warning: InfiniteScroll: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)
```

Introduced in #88, but it is always `undefined`. The reason the list is refreshed, is because the parent component will recreate the `InfiniteScroll` on change of key.

**Comment by daggmano** [comment]
Can this property be renamed to `dataSetId` (or something else) rather than `key`?

**Comment by ankeetmaini** [comment]
PRs welcome!

**Comment by daggmano** [comment]
Turns out that adding the `key` prop was not actually necessary in the first place. React automatically re-creates the component on key change anyway...
