### ISSUE TITLE
Not loading correct # of obects when there's only one left to fetch.

### ISSUE THREAD

**Issue by kirasiris** [ankeetmaini/react-infinite-scroll-component#179]
Hello, this is actually my first time implementing this library and let me tell you, it is incredible!.

However as I soon as I decided to test it, I got an error on my end and the thing is, let's say, I have 11 posts in total. The first page loads 5 then I scroll down, it fetches 5 more, there is still one post left which is not fetched.

Not problem at all, I mean is just one single post but the thing is that after fetching the 11 posts(I have a 'load-more' button to be shown in case there's an error with the scrolling), it keeps showing the string on 'loading...'

This is actually what I get from console.log() it
```
index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: InfiniteScroll
```
This is actually the code I'm using:
```
const params = `?page=${page}&limit=${limit}`;
  useEffect(() => {
    getTimeline(params);
  }, []);

  // HANDLE TIMELINE
  const loadMore = () => {
    getTimeline(params);
  };
```
Is there any solution to this?

**Comment by njagsarran-pm** [comment]
Did you find a solution? I'm having the same problem
