### ISSUE TITLE
Should this work in a functional component?

### ISSUE THREAD

**Issue by ElixirMike** [ankeetmaini/react-infinite-scroll-component#183]
I am trying to implement this in a functionali component, but it's not working. should it work or does it only work from class based component?

**Comment by KanzakiYui** [comment]
Yeah same here, using in a functional component, failed to work!

**Comment by RomanShabanov** [comment]
It works just fine with the functional component.

https://codesandbox.io/s/vigorous-borg-khsq3

**Comment by ElixirMike** [comment]
Stange, it's not working for me. Is there an issue when using it in a modal? That's how I'm trying to implement it.

**Comment by heniotierra** [comment]
I'm also having problems using this lib inside a modal with functional components. The `next` function is not being called. I'm using Material's modal component.

**Comment by brunnohofmann** [comment]
@heniotierra  I had the same problem, but only if my data has no enough data (only 4 objects) to activate a scrollable window. Try to reduce your navigator height. 
Im still trying to solve this problem.

**Comment by davidpelayo** [comment]
Same issue here. My next function isn't being called correctly, as @heniotierra

**Comment by atellezsazo** [comment]
Same issue here

**Comment by ankeetmaini** [comment]
For `next` function to be called your component needs to have enough rows to force a scroll. The component attaches a listener on `scroll` and then calls the next function. You can try by fetching enough records to cause a scroll.

**Comment by ankeetmaini** [comment]
Closing this issue as `Functional` components work too. Please open another with a repro. Thanks  :)

**Comment by v1talii-dev** [comment]
`next` function not work in modal dialog...

**Comment by martin-landhi** [comment]
@v1talii-dev coud you fix that issue on modals?
