### ISSUE TITLE
Does this work if our initial data set is large?

### ISSUE THREAD

**Issue by russiandobby** [ankeetmaini/react-infinite-scroll-component#186]
My  issue is what if our initial array is long, say 150 elements, how can i make it that it only shows 20 elements at a time? I been playing with the first infinite scroll example but when i set `items: Array.from({ length: 150 })`, llazy just load those 150 elements and then it lazy loads the rest, how can i make it so that it only loads chunks of 20?

**Comment by OmarMoataz** [comment]
Hi, russiandobby.

This should work even if the dataset is too large. You just need to keep the data in a separate array and then append to the main array (the one that's responsible for holding the data being rendered) as the next function gets called.
