### ISSUE TITLE
Hiding endMessage is not intuitive.

### ISSUE THREAD

**Issue by MatthewCallis** [ankeetmaini/react-infinite-scroll-component#19]
I just wanted to hide the endMessage but doing so it not intuitive, setting it to `''`, `false` or `null` just shows the default, you have to set it to `' '` to actually hide the message when you don't want to show anything (including the cute default).

**Comment by ankeetmaini** [comment]
Thanks for the issue. This is being addressed in #25. I'll release a version soon!

**Comment by ankeetmaini** [comment]
@MatthewCallis you can now remove the hack, v2.4.0 fixes this 😄
