### ISSUE TITLE
Nesting element (div) in endMessage throws warning

### ISSUE THREAD

**Issue by nealoke** [ankeetmaini/react-infinite-scroll-component#20]
Currently implementing this component however, I don't think it makes sense that the `endMessage` prop only takes text. Should be able to just pass component without any styling by this component.

When I pass it a div with some content it throws the following error: 

`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. See ReviewList > InfiniteScroll > p > ... > InfoBox > div.
`
Please fix this issue ;) I've never made a pull request and don't have a clue on how to do it ;)

**Comment by ankeetmaini** [comment]
Hi @nealoke yep I know this is an issue. We're solving it in #25!

**Comment by ankeetmaini** [comment]
Fixed this in v2.4.0!
