### ISSUE TITLE
Inverse scrolling not working in example

### ISSUE THREAD

**Issue by mserranom** [ankeetmaini/react-infinite-scroll-component#209]
Tested in Chrome 85/Mac, the `ScrolleableTop.tsx` example is not working. I'm unable to scroll through the example.

https://github.com/ankeetmaini/react-infinite-scroll-component/blob/e5863aa61d0d161cbe1231722e0321fa7d0764e1/src/stories/ScrolleableTop.tsx

See codesandbox:

https://codesandbox.io/s/cool-cori-s75k2?fontsize=14&hidenavigation=1&theme=dark

**Comment by osmarpb97** [comment]
Hi! @mserranom you can post some pics?

**Comment by osmarpb97** [comment]
![image](https://user-images.githubusercontent.com/36203999/93119444-714b4e80-f687-11ea-9b89-8c5f6f0288a5.png)
I couldt reproduce the error I tried it in broswerstack emulating a mac and version 85 of chrome and everything seems to run as it should

**Comment by osmarpb97** [comment]
Did you scroll over the div? or on the body?

**Comment by mserranom** [comment]
Seems it's working, I would swear I tried scrolling in many different places 😓 
Thanks!
