### ISSUE TITLE
Scroll top in inverse fires next when scrolling bottom

### ISSUE THREAD

**Issue by ozcanonur** [ankeetmaini/react-infinite-scroll-component#218]
See [https://react-infinite-scroll-component.netlify.app/?path=/story/components--infinitescrolltop](url)

**Comment by AlaDouagi** [comment]
@ozcanonur The link you posted doesn't refer to anything relevant, please clarify how to overcome the bug.

**Comment by MarcusOy** [comment]
I was getting the same problem, but it seems like this behavior was patched between `5.1.0` and 6.1.0` as I've recently upgraded between these two versions and that bug seemed to go away. Unrelated, but `rm -rf node_modules/` then `yarn` helped to get rid of older, broken version.
