### ISSUE TITLE
Inverted scroll list is not triggering next function 

### ISSUE THREAD

**Issue by salatielq** [ankeetmaini/react-infinite-scroll-component#220]
I'm trying to use react-infinite-scroll-component to create a chat where the newest messages are at the bottom so if the user scrolls to the top it loads the old messages.

So I just copied the CodeSandbox example and tried to invert the scroll as [documented here](https://github.com/ankeetmaini/react-infinite-scroll-component#using-scroll-on-top) but the `next` function is **NOT** been triggered

You can see here: https://codesandbox.io/s/dawn-feather-szuzm

I don't know if needs some additional config to work. Anyone can help? thank you!

EDIT: I tested on Brave Version 1.15.75 Chromium: 86.0.4240.99 and Chome Version 86.0.4240.111

**Comment by brechtwaeghe** [comment]
Hi, 
I had the same issue, just change your package json to the latest version 5.1.0 & it will work.

**Comment by salatielq** [comment]
> Hi,
> I had the same issue, just change your package JSON to the latest version 5.1.0 & it will work.

Thank you!!
