### ISSUE TITLE
Mysterious 0

### ISSUE THREAD

**Issue by ghuffman** [ankeetmaini/react-infinite-scroll-component#225]
![image](https://user-images.githubusercontent.com/43155215/98731088-d0190580-2362-11eb-8167-bf8869b6c54a.png)

Any idea where this mysterious 0 might be coming from? Looking through source but it's not jumping out at me. Associated to endMessage, loading message doesn't add the 0.

Thanks for any ideas -

**Comment by IcanDivideBy0** [comment]
this can happens with React when you do someting along the lines:
```js
<div>
  {myArray.length && <div>Array has content!</div>}
</div>
```

when `myArray` is empty, `myArray.length` is 0, thus is falsy, but 0 is returned to react tree, which display 0

**Comment by xyide** [comment]
I've encountered the same thing and due to the same reason that @IcanDivideBy0 mentioned.  To resolve it, use the !! feature like so to force a boolean instead of a falsy value.
```
{!!myArray.length && <div>...</div>}

**Comment by IcanDivideBy0** [comment]
Or to make it more explicit
```jsx
{Boolean(myArray.length) && <div>...</div>}
```

**Comment by ghuffman** [comment]
Thanks everyone, exactly what I needed

**Comment by ghuffman** [comment]
Setting hasmore to integer value instead of boolean caused the 0 to show up. Perfectly rational, docs are clear to use a boolean not integer. Posting in case someone else runs into. Thanks for above, it led me right to the issue.
