### ISSUE TITLE
Want to hide scroll bars

### ISSUE THREAD

**Issue by mrdale1958** [ankeetmaini/react-infinite-scroll-component#23]
I'm using your package on a large touchscreen and I'd rather not see scroll bars but I don't see a way to override your overflow: auto style

**Comment by mhd999** [comment]
There is Style props allow you to over ride the default css.

> Style: any style which you want to override


`style={{ overflowY: 'hidden' }}`

**Comment by ankeetmaini** [comment]
Hi @mhd999 as far as I can think, removing scroll will not trigger new fetches of the data. Which scrollbar are you referring too?

**Comment by mhd999** [comment]
My answer above is just about how to override default style, but i agree with no scroll bar no fetch will be triggered.

**Comment by Juliomerlos** [comment]
I think this is not a real solution because wrapping the infinite scroll with a div with overflow:hidden makes the infinite scroll stop working and you hace to implement many other things, which is the reason you are using infinite-scroll-component.

**Comment by NamJiwony778** [comment]
I could hide scroll but keep functionality only combining inline styles and css file. It doesn't work only with css file.
<div
        id="scrollableDiv"
        className={styles.scrollbarContainer}
        style={{
          height: 400,
          width: '100%',
          overflow: 'auto',
          scrollbarWidth: 'none', // hide for Firefox
        }}>
        <InfiniteScroll
          dataLength={data.length}
          hasMore={data.length < 50}
          scrollableTarget="scrollableDiv"
        >
       ...some code
     </InfiniteScroll?>
</div>


css code for hiding for safari, opera and chrome

.scrollbar-container::-webkit-scrollbar {
   display: none;
}

**Comment by cassioseffrin** [comment]
The @mhd999 hack have worked very well. +1
