### ISSUE TITLE
Bidirectional infinity

### ISSUE THREAD

**Issue by mrdale1958** [ankeetmaini/react-infinite-scroll-component#24]
This component has been an enormous help but (I fear) it has a fatal flaw for part of my use case.

I have a list of ~100k alphabetized names in my large touchscreen table application.  While the enormous task scrolling through it is actually a key part of the interaction, sometimes the user has other needs and I've given them a set of letter buttons to jump around in the list.  The approach of just rewriting the divs array is fairly satisfying until they want to scroll up.  I'm currently surviving by using refreshFunction to prepend a new page of data on divs which obviously causes a flash rather than a scroll.  Is there a ReactJS-y way to access where the 'top' of the scrolling div is going to start?

**Comment by ankeetmaini** [comment]
Scrolling up has just been added to the latest version. Although both directions feature doesn't exist. Please open a separate issue if you want it added. PRs welcome too :)
