### ISSUE TITLE
scrollableTarget naming problem

### ISSUE THREAD

**Issue by hodev-dev** [ankeetmaini/react-infinite-scroll-component#246]
props should be lower case 
scrollabletarget
```
React does not recognize the `scrollableTarget` prop on a DOM element. If you intentionally want it to appear in the DOM as a 

custom attribute, spell it as lowercase `scrollabletarget` instead. If you accidentally passed it from a parent component, remove it 

from the DOM element.
```

**Comment by vj-abishek** [comment]
It works fine for me. Check this example [Example](https://github.com/ankeetmaini/react-infinite-scroll-component#using-scroll-on-top).

Please provide your code, which is causing this issue.

**Comment by hodev-dev** [comment]
it got fixed thank you,
 the problem was typescript 
i used wrong interface
you can close it now
