### ISSUE TITLE
🤖 integrate all-contributors bot

### ISSUE THREAD

**Issue by iamdarshshah** [ankeetmaini/react-infinite-scroll-component#249]
- [ ] Install all-contributors bot to this repo - [docs](https://allcontributors.org/docs/en/bot/installation) [@ankeetmaini to update]
- [ ] Configure all-contributors bot - PR: #248 (InProgress)
- [ ] Add contributors details (Pending)

> Note: This is part of Roadmap 7.0 #247 development. This issue will focus more on tracking individual feature/bug's progress.

**Comment by ankeetmaini** [comment]
Thanks this is done!
