### ISSUE TITLE
Usage example for static data

### ISSUE THREAD

**Issue by yarnball** [ankeetmaini/react-infinite-scroll-component#26]
Hi,

I would like to use this on a large list of static/offline data. However, I have been unable to implement it. Basically, I want it to only get say 100 results from the map at `this.state.demoData`. Then once I reach the refresh point, it should get 100 more results.

I am wanting to use infinite scroll to improve performance (as the list will be long, and have a lot of data in it such as images )

I have not been able to implement it. I put this in a codeSandBox https://codesandbox.io/s/xvlR245VE

Here is my code:

```
class App extends React.Component {
  constructor() {
    super();
    this.state = {
      demoData: x.demoData,
    };
  }
  generateDivs = () => {
    let moreDivs = [];
    let count = this.state.demoData.length;
    for (let i = 0; i < 30; i++) {
      moreDivs.push(
        this.state.demoData.map(e => {
            <span key={e.id}> {e.name} </span>
        }));
    }
  }
  render() {
    return (
        <div style={{overflow: 'auto', maxHeight: 500}}>
test
        <InfiniteScroll
          next={this.generateDivs}
          hasMore={true}
          loader={<h1>Loading...</h1>}>
          {this.state.demoData}
        </InfiniteScroll>
      </div>
    );
  }
}
```

I've also put it in a code sandbox:

https://codesandbox.io/s/xvlR245VE

**Comment by ankeetmaini** [comment]
I hope you got it working. Apologies for not getting to it earlier. Please reopen if this is still an issue.

**Comment by Leden4ik** [comment]
open.

You need a normal example to work with static/offline  data
