### ISSUE TITLE
infinite fetchMoreData

### ISSUE THREAD

**Issue by Doedelpumpe** [ankeetmaini/react-infinite-scroll-component#260]
I have a useState object array which i want to map with infinite scroll. I tried to slice 30 elements into another array and map it. works. But my fetchMoreData is running from the beginning and does not stop. Feels like the code does not get the info if the user hits the last element in the array.
I am trying to run the InfiniteScroll inside a Function component not a class component. Not sure if that does matter.

**Comment by ankeetmaini** [comment]
Would you be able to give a repro, I'm afraid I don't understand your
usecase

**Comment by Doedelpumpe** [comment]
Of course i can give u a code snippet:
```
function Library() {
const [songDbList, setSongDbList] = useState([]);
const [songList, setSongList] = useState ([]);
const songListAddValue = 30;

useEffect(() => {
...
setSongDbList(response.data);
...
}

const fetchMoreData = () => {
    setTimeout(() => {
      const temp = songList.length + songListAddValue;
      const tempArray = songDbList.slice(songList.length, temp)
      setSongList(songList.concat(tempArray));
    }, 5000);
  }

return (
<div className="Library">
      <div id="content" className="content">
        <InfiniteScroll
          dataLength={(songList.length)}
          next={fetchMoreData()}
          hasMore={true}
          loader={<h4>Loading...</h4>}
        >
          {songList ? songList.map((val, index) => (
            <tr key={val.id} style={style} key={index}>
              <td className="info">
                <h3>{val.title}</h3>
                <p>{val.artist}&nbsp;</p>
              </td>
              <td className="duration">
                <p>{secondsToRender(val.duration)}</p>
              </td>
              <td className="buttons">
                <button id={"upvote" + val.id} className="upvote" onClick={() => upvote(val)}><b><span>&#43;</span> </b></button>
              </td>
              <td className="votes" id={val.id}>
                {val.votes}
              </td>
              <td className="buttons">
                <button id={"downvote" + val.id} className="downvote" onClick={() => downvote(val)}><b><span>&#8722;</span> </b></button>
              </td>
            </tr>
          )) : "" }
        </InfiniteScroll>
      </div>
    </div>
)
```

there might be some generel mistakes because i was testing a lot due to the infinite fetchMoreData-issue.

**Comment by dieudonneAwa** [comment]
I am facing a similar issue. I'm using it to infinitely fetch data from an API when scrolling down a page. However, it shows an infinite loading when the content of the first pagination are already in the viewport.

I expect it to fetch more data if the first set of the data is visible already. I expect it to continue fetching as long as it will be visible to the user.

**Comment by Doedelpumpe** [comment]
I thought it might have a conflict to my CSS but i took all styling out and it still hit the fetchMoreData-Function while i load the page and stay on the upper most top of the page in a infinite way. I had a look at the InfiniteScroll-code and as i understand it, the "next" call should be done once when the bottom of the page is hit. 
Tested it in firefox and chrome.

**Comment by ankeetmaini** [comment]
@Doedelpumpe you've to pass a function to `next`, instead you're calling the function which is not correct.

```js
next={fetchMoreData}
```

Please try this

**Comment by Doedelpumpe** [comment]
@ankeetmaini Thanks ankeet. Seems to work now :-) massive thumbs up!
