### ISSUE TITLE
How to add a custom class?

### ISSUE THREAD

**Issue by edgar-petrovskis** [ankeetmaini/react-infinite-scroll-component#27]
Hi,

I would like to add some custom class instead "infinite-scroll-component". How can I do this?

Thanks

**Comment by ankeetmaini** [comment]
As of now I don't take any prop to pass a prop for a custom className. You can always add rules for the class `infinite-scroll-component`, or pass a children wrapped in a div to which you can give a custom classname like

```jsx
<InfiniteScrollComponent
 // props omitted for brevity
>
  <div className="your-custom-class">
    {list of items}
  </div>
</InfiniteScrollComponent>
```

This way you can have all the scrollable content inside a parent with your class. Let me know if this works and if not, what use case are you solving for.

Thanks for checking this out!

**Comment by edgar-petrovskis** [comment]
Thanks!
I just wanted to use custom class in case if the component will be updated and class will be changed.

**Comment by Aman-aj123** [comment]
nice
