### ISSUE TITLE
Scroll doesn't work fine 

### ISSUE THREAD

**Issue by ssageghi** [ankeetmaini/react-infinite-scroll-component#28]
Hi
I used your component and when I scroll down it worked fine once
but at the second time I should scroll up and down to perform loading data
and it doesn't work if I just scroll down

**Comment by ankeetmaini** [comment]
Hi @ssageghi can you try this the component in the demo here? http://ankeetmaini.github.io/react-infinite-scroll-component/

It appears to be loading fine, could you check if your next function is called when the scroll is near the bottom. Can you checkout the examples from this location and see if you've used it the same way?
https://github.com/ankeetmaini/react-infinite-scroll-component/blob/master/demos/no-height.js#L62

**Comment by ssageghi** [comment]
I try the demo 
next function doesn't call 
and I use the same way

**Comment by ankeetmaini** [comment]
can you show me your code?

**Comment by ankeetmaini** [comment]
Closing this because of a lack of response. Hoping you figured out!

**Comment by AmauryLiet** [comment]
@ankeetmaini
I just spent some time facing the same issue:
It could be reproduced with a `refreshFunction` function being too fast (simply a setState with mocked data)
I "fixed" the issue by simulating network latence with a setTimeout(...).

By analysing the component state, it appeared that `state.actionTriggered` remains `true` until the user scrolls up again.

Hoping this gives you more insight on the bug ;)

**Comment by VinayakBagaria** [comment]
@AmauryLiet  Can you provide a code snippet for your fix on the issue?
