### ISSUE TITLE
How do i use it with Modals?

### ISSUE THREAD

**Issue by dhwrwmgwra** [ankeetmaini/react-infinite-scroll-component#29]

**Comment by fabioimpe** [comment]
+1
I'm trying to use it in a modal component, but even passing the reference of the container with the **scrollableTarget** property, the **next** function is not triggered...
@ankeetmaini any help please?

**Comment by ankeetmaini** [comment]
Hi guys, this is because the parent Modal renders when the child
(InfiniteScroll) renders. So when InfiniteScroll renders and its
componentDidMount is called the parent's ref is null. So the event
listeners are set at window, but in case of Modal the window doesn't
scroll. I'm working at a fix, I'll post my solution let me know if you like
it.

**Comment by fabioimpe** [comment]
Thank you, in the meantime I found a workaround, I tried to set a fixed height to the InfiniteScroll component and it started to work also in the modals, in my case I set it as window.innerHeight, just because my modal is fullscreen.

**Comment by ankeetmaini** [comment]
Yes, that'll always work, if you pass height to InfiniteScroll component.

**Comment by igorarkhipenko** [comment]
@ankeetmaini Hey, have you ever found a solution for it? I'm having the same issue but the height of Modal component is not known before it gets rendered. I wonder if there's a way to use InfiniteScroll inside that in this case? Thanks.

**Comment by mislavmiocevic** [comment]
@igorarkhipenko 

Maybe this example will help you.
It was based by callback ref:
https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node

```
import { render } from "react-dom";
import React, { useCallback, useState } from "react";
import InfiniteScroll from "react-infinite-scroll-component";

const InfiniteScrollComponent = () => {
  const [items, setItems] = useState(Array.from({ length: 30 }));

  const listItems = items.map((_, index) => <div key={index}>{index}</div>);

  const [listItemsContainerRef, setListItemsContainerRef] = useState();

  const onlistItemsContainerRefChange = useCallback((node) => {
    if (node !== null) {
      setListItemsContainerRef(node);
    }
  }, []);

  return (
    <div
      style={{
        height: "300px",
        // height: 'calc(100vh - 100px)', // this works also
        display: "flex",
        flexDirection: "column",
        background: "lightyellow"
      }}
    >
      <div style={{ padding: "20px", background: "lightblue" }}>Header</div>

      <div ref={onlistItemsContainerRefChange} style={{ overflow: "auto" }}>
        {listItemsContainerRef && (
          <InfiniteScroll
            dataLength={listItems.length}
            next={() => {
              window.setTimeout(() => {
                setItems((prevItems) => [
                  ...prevItems,
                  ...Array.from({ length: 30 })
                ]);
              }, 1500);
            }}
            hasMore={true}
            loader={<p style={{ color: "red" }}>...loading</p>}
            scrollableTarget={listItemsContainerRef}
          >
            {listItems}
          </InfiniteScroll>
        )}
      </div>
    </div>
  );
};

const App = () => {
  const [visible, setVisible] = useState(false); // faking modal show

  return (
    <div>
      <button onClick={() => setVisible(true)}>show</button>
      <button onClick={() => setVisible(false)}>hide</button>

      {visible && <InfiniteScrollComponent />}
    </div>
  );
};

render(<App />, document.getElementById("root"));
```

**Comment by thudaohd** [comment]
i have same issue. is there any solution?

**Comment by martin-landhi** [comment]
@ankeetmaini coud you find a solution to that isssue?

**Comment by AbdulMoiz96** [comment]
```
import React, {useCallback, useState} from "react"
import InfiniteScroll from "react-infinite-scroller"
import {Table} from "antd"

const ScrollableTable = props => {
    
    const outerDivStyle = {height: '500px', overflow: 'auto'}
    const [tableContainerRef, setTableContainerRef] = useState()

    const onTableContainerRefChange = useCallback(node => {
        if (node !== null) {
            setTableContainerRef(node)
        }
    }, [])

    const fetchData = () => {
        // Fetch your data here. 
    }

return <div className="w-100" style={outerDivStyle} ref={onTableContainerRefChange}>
          <InfiniteScroll
              hasMore={true}
              initialLoad={false}
              loadMore={fetchData}
              useWindow={false}
              scrollableTarget={tableContainerRef}
          >
              <Table {...props}/> 
        </InfiniteScroll>
</div>
```

@martin-landhi, as @mislavmiocevic suggested, the above code works for me.

The additional thing I did, was just added `useWindow={false}`.

**Comment by atharhashmi** [comment]
@AbdulMoiz96 Awesome! This solved a major issue for us that we were struggling with for quite some time...

**Comment by supuwoerc** [comment]
Although I passed height to fix the problem, strangely enough, my code executed normally in the development environment, build deployment to the production environment only found this error, I looked at the source code, against the window binding event to locate the error, too strange, I do not understand why the development environment is normal...
![image](https://github.com/ankeetmaini/react-infinite-scroll-component/assets/36561218/33a0b6e3-b504-4943-a06a-6cb808b6f3de)

**Comment by supuwoerc** [comment]
> 虽然我通过了height来解决问题，但奇怪的是，我的代码在开发环境中执行正常，构建部署到生产环境才发现这个错误，我查看了源代码，针对窗口绑定事件定位了错误奇怪，不明白为什么开发环境正常... ![图像](https://user-images.githubusercontent.com/36561218/256565731-33a0b6e3-b504-4943-a06a-6cb808b6f3de.png)

I found the reason. It's something I did with the ui lib，https://github.com/ant-design/ant-design/issues/43508
