### ISSUE TITLE
New items are not loading/list isn't re-rendering when scrolled to bottom

### ISSUE THREAD

**Issue by EricHasegawa** [ankeetmaini/react-infinite-scroll-component#308]
I feel like I am missing something obvious - I am setting this up in a functional component, but when I scroll to the bottom, no new data loads. I can see fetchMore is being called, and itemCards is growing (I checked length before and after the fetchMore call), but no new data is displayed. What am I missing here? Attaching the code below.

`export default function Catalog({ search_query }) {

    useAPICall('browse', {query: search_query})
    const browseData = useSelector(state => state.browseData)

	var itemCards = browseData.map((item) => (
        <ItemCard key={item.id} data={item}></ItemCard>
    ))

    const fetchMore = () => {
        for (var i= 0; i < 20; i++) {
            itemCards.push(itemCards[i])  
        }
    }

    return (
        <div className='catalog'>
            <InfiniteScroll
                dataLength={itemCards.length} //This is important field to render the next data
                next={fetchMore}
                hasMore={true}
                loader={<h4>Loading...</h4>}
                endMessage={
                    <p style={{ textAlign: 'center' }}>
                    <b>Yay! You have seen it all</b>
                    </p>
                }
                // children={itemCards}
                >
                    {itemCards}
            </InfiniteScroll>
        </div>
    )
}`

**Comment by BenDLH** [comment]
You need `itemCards` wrapped in `useState()`, no? Otherwise no re-render will be triggered.

**Comment by EricHasegawa** [comment]
> 
> 
> You need `itemCards` wrapped in `useState()`, no? Otherwise no re-render will be triggered.

So do the items in your list need to be a state variable? Mine are just a standard variable

**Comment by BenDLH** [comment]
Yes

**Comment by EricHasegawa** [comment]
Thanks so much! Working with functional components I didn't get this. Cheers!

**Comment by utiq** [comment]
@EricHasegawa can you post how did you end up doing it?

**Comment by EricHasegawa** [comment]
For sure - basically, `var [items, updateItems] = useState(browseData)` where items is the items in the list. And when you have your fetching function - `updateItems(items.concat(itemCards2))` where the bracketed part of updateItems updates your items variable.
