### ISSUE TITLE
Suggest, the height Param can accept a percent string

### ISSUE THREAD

**Issue by elysianaries** [ankeetmaini/react-infinite-scroll-component#31]
height = { 300 } may be only use unit 'px' ， I mean  height = { 80% } , it will be helpful

**Comment by ankeetmaini** [comment]
You can give `80%` in string. It accepts either a number or a string. I'm closing this issue. Please feel free to reopen if you encounter a problem. Thanks!

**Comment by AdityaParameshwara** [comment]
Hi,
The provided the percentage in strings. The scroll bar doesn't show up. However if I give just the number (which defaults to pixel), the scrollbar is visible

**Comment by ipanasenko** [comment]
This behavior broke in v5, because in types `height` is specified as `number` only

**Comment by ankeetmaini** [comment]
Thanks! I published a new patch version which fixes the problem.
