### ISSUE TITLE
Not able to scroll and get the new results

### ISSUE THREAD

**Issue by rexyou0831** [ankeetmaini/react-infinite-scroll-component#370]
Hi there,

I'm new to use this library, just wondering why my side next props not working to get the next page, am I doing wrong?

` const Results = () => {

    const [ responseData, setresponseData ] = useState([]);
    const [ page, setPage ] = useState(1);
    const [ totalPage, setTotalPage ] = useState(1);
    const [ totalLength, setTotalLength ] = useState(0);
    const [loading, setLoading] = useState(false);

    const fetchData = async () => {

        if (loading) return;
        setLoading(true);
        
        try {
            await axios.get(`http://sampleurl/api/?page=${ page }`)
            .then((response)=>{
                console.log(response.data.users)
                setresponseData(prev => [...prev, ...response.data.users.data]);
                setTotalLength(response.data.users.total)
                setTotalPage(response.data.users.last_page)
                setPage( page + 1 )
            })   
        } catch (error) {
            console.log(error)
        } finally {
            setLoading(false);
        }

    };

    useEffect(()=>{
        
        fetchData()

    }, [])

    return (
        <div className=' w-5/6 mx-auto mt-10 h-full overflow-auto' id="scrollableDiv">
            
            <InfiniteScroll 
                dataLength={ totalLength } 
                next={ fetchData } 
                hasMore={ true }
                isLoading={loading}
                scrollableTarget="scrollableDiv"
            >
                <ResponseList responseData={responseData}/>
            </InfiniteScroll>

            <div className=' fixed w-12 h-12 bg-black bottom-44 right-0 rounded-tl-lg rounded-bl-lg text-white flex items-center justify-center'>
                <FaSearch className='text-2xl' />
            </div>

            <div className=' fixed w-12 h-12 bg-black bottom-28 right-0 rounded-tl-lg rounded-bl-lg text-white flex items-center justify-center'>
                <FaFilter className='text-2xl' />
            </div>

            <div className=' fixed w-12 h-24 bg-black bottom-0 right-0 rounded-tl-lg text-white flex flex-col text-center text-md items-center justify-center'>
                <span>{ page }</span>
                <span>----</span>
                <span>{ totalPage }</span>
            </div>
        </div>
    )`

**Comment by mehmood-v** [comment]
facing the same issue

**Comment by dustyjay** [comment]
same here. has there been any update on this?

**Comment by dustyjay** [comment]
i found a solution to mine. turns out i was passing the wrong value to the `dataLength` prop

`dataLength` should carry the length of the `last_page` in your case @rexyou0831 
```
<InfiniteScroll
  hasMore={true}
  next={() => fetchMoreData()}
  dataLength={orders.length}
  loader={<p className="text-center mt-8">Loading more orders...</p>}
  endMessage={<p className="text-center mt-8">End of list</p>}>
    <LiveTripCards orders={localOrders} />
</InfiniteScroll>
   ```

**Comment by rexyou0831** [comment]
hi @dustyjay thanks for the suggestion but my side found out that I need to separate the axios function call
The height also causing the problems not continue call API.
Here is my current solution sample

`import { useEffect, useState } from 'react';
import './App.css';
import InfiniteScroll from 'react-infinite-scroll-component';
import axios from 'axios';
import { Lists, Loader, Endpage, SearchModal } from './components';

function App() {

  const [dataSource, setDataSource] = useState([]);
  const [hasMore, setHasMore] = useState(true);
  const [total, setTotal] = useState(0);
  const [currentTotal, setCurrentTotal] = useState(0);
  const [pageNumber, setPageNumber] = useState(2);
  const [displayPage, setDisplayPage] = useState(1);
  const [totalPage, setTotalPage ] = useState(0);

  useEffect(()=>{
    axios.get(process.env.REACT_APP_API_URL).then(response=>{
      // console.log(response.data)
      setDataSource(response.data.users.data)
      setTotal(response.data.users.total)
      setCurrentTotal(response.data.users.to)
      setTotalPage(response.data.users.last_page)
      setDisplayPage(1)
      setHasMore(true)
    })
  }, [])

  const fetchMoreData = () => {

    if(currentTotal < total){ 

      setPageNumber(prev => prev + 1);

      setTimeout(() => {
        axios.get(process.env.REACT_APP_API_URL+`/?page=${ pageNumber }`).then(response=>{
          console.log(response.data)
          setDataSource(prev => [ ...prev, ...response.data.users.data ])
          setTotal(response.data.users.total)
          setCurrentTotal(response.data.users.to)
          setTotalPage(response.data.users.last_page)
          setDisplayPage(prev => prev + 1)
        })
        // setDataSource(dataSource.concat(Array.from({ length: 20 })));
      }, 1500);

    }
    else {
      setHasMore(false)
    }

  }

  return (
    <div className=' w-5/6 mx-auto mt-5'>
      <InfiniteScroll 
          dataLength={ dataSource.length } 
          next={fetchMoreData} 
          hasMore={ hasMore }
          loader={ <Loader /> }
          endMessage={ <Endpage /> }
          // height={ 550 }
      >
        <Lists dataSource={ dataSource } />
      </InfiniteScroll>
      {/* <button className=' fixed w-12 h-12 bg-black bottom-28 right-0 rounded-tl-lg rounded-bl-lg text-white flex items-center justify-center' onClick={ showCtrl }>
          <FaSearch className='text-2xl' />
      </button> */}

      <div className=' fixed w-12 h-24 bg-black bottom-0 right-0 rounded-tl-lg text-white flex flex-col text-center text-md items-center justify-center'>
          <span>{ displayPage }</span>
          <span>----</span>
          <span>{ totalPage }</span>
      </div>
      <SearchModal />
    </div>
  );
}

export default App;`
