### ISSUE TITLE
Set scrollable container?

### ISSUE THREAD

**Issue by nero120** [ankeetmaini/react-infinite-scroll-component#39]
Hi @ankeetmaini, I'm using your component for a plugin I'm building and I can say that so far it's much better than most of the other React infinite scrollers I've tried so thank you!

My only issue is that the application that my plugin will be displayed in never scrolls on document.body, it uses a scrollable container div for displaying content inside. Because of this, if I don't use the `height` prop, `next` never triggers. If I do use `height` then everything works except that the user now has two sets of scroll bars, one on the applications scrollable container and one on the infinite scroll component. This is a bit of an ugly experience so I was wondering if there's any way of setting the target scrollable container to a particular element? That way `next` could be trigger when then user scrolls to the bottom of the application's scrollable container. Hope that makes sense!

**Comment by ankeetmaini** [comment]
Okay, I see. It seems possible. We can pass in a target which will default to document.body

I'll try to do this in a day or two. And PRs are always welcome!

**Comment by nero120** [comment]
Since it's Christmass... (https://github.com/ankeetmaini/react-infinite-scroll-component/pull/40) 😄 

I haven't refactored any of the existing code, but you could set ancestorScroll to document.body by default if you think that would be better.

**Comment by ankeetmaini** [comment]
Fixed with #40
