### ISSUE TITLE
Infinite Scroll targeting on a parent div does not load the details 

### ISSUE THREAD

**Issue by samikroy** [ankeetmaini/react-infinite-scroll-component#45]
While targeiiing a outer div than the immendiate parent div for infinite scroll, function call happends for 
next property but the items does not load in the UI.

Code Sample

<InfiniteScroll
                                                              
                                    next={this._loaditems.bind(this) }
                                    hasMore={this.state.hasMoreItems}
                                    scrollableTarget= {this._returnParent() }
                                    scrollThreshold={0.5}
                                    >
                                    <DetailsList
                                        items={this.state.items}
                                        columns={_itemColumns}
                                        layoutMode={DetailsListLayoutMode.fixedColumns}
                                        checkboxVisibility={CheckboxVisibility.hidden}
                                        compact={true}
                                        onRenderRow={this._onRenderitem.bind(this) }
                                        />
                                </InfiniteScroll>

//this._returnParent() - returns the parent div object.

**Comment by ankeetmaini** [comment]
Can you share a reproduceable sample in codesandbox.io like this
https://codesandbox.io/s/k90wzm7pnv. It'll help me debug this quickly

**Comment by ankeetmaini** [comment]
Please re-open if your issue still persists.

**Comment by VladimirMilov** [comment]
@ankeetmaini, I have a problem with the scrollableTarget. 
Here is a code snippet: 
<div style={{ overflow: 'scroll' }} ref={c => (this.myDiv = c)}>
        <InfiniteScroll
          next={loadMore}
          hasMore
          loader={<h4>Loading...</h4>}
          scrollableTarget={this.myDiv}
          style={{ padding: '0.5em' }}
        >
          {this.props.info.length === 0 && <p>There is no information</p>}
          {this.props.info.map(info=> (
            <MyComponent ... />
          ))}
        </InfiniteScroll>
      </div>
I should be missing something small.

**Comment by ankeetmaini** [comment]
There's no need to pass scrollableTarget in your case. By default it will
add scroll on window, or if you give it a height it'll create a div of that
height and render your content.

**Comment by VladimirMilov** [comment]
The problem is that I am using display flex and I want my upper div to have overflow: scroll.
I can put some height with %, but it doesn't work. Also, i am not scrolling the window, just a div inside the document. Can you please see these lines and say what is wrong.
<div style={{ overflow: 'scroll' }} ref={c => (this.myDiv = c)}>
scrollableTarget={this.myDiv}
