### ISSUE TITLE
Scrollbar does not appear with using % for height

### ISSUE THREAD

**Issue by AdityaParameshwara** [ankeetmaini/react-infinite-scroll-component#48]
When I give the height in %, the scrollbar disappears

**Comment by ankeetmaini** [comment]
% doesn't work reliably for height, try to give in `vh` or pixel. Let me know if it works? Please re-open if it doesn't.

**Comment by AdityaParameshwara** [comment]
It worked with vh. But please try to make % work. That would be great!
