### ISSUE TITLE
2-way scroll

### ISSUE THREAD

**Issue by ddeath** [ankeetmaini/react-infinite-scroll-component#49]
I have a proposal for the new feature.
It would be nice if the component had an option to infinite scroll in both directions.
It would be useful on timelines where you start in the middle. For example when you want to show present, but also want to be able to scroll into the past or future.

**Comment by landon9720** [comment]
A semi-related request is to also support **horizontal** infinite scroll.

**Comment by ankeetmaini** [comment]
We just merged the up direction scroll support. This issue is quite old, do open a fresh one and PRs welcome too :)
