### ISSUE TITLE
Add pull down to refresh as well?

### ISSUE THREAD

**Issue by kdenz** [ankeetmaini/react-infinite-scroll-component#5]
Great library that actually works! I realized no other React.js infinite scroll components support both pull down to refresh and pull up to load more, if this can be implemented as well, it could be make this library a killer!

**Comment by ankeetmaini** [comment]
That sounds really fantastic! I can take it up next weekend. 😀

**Comment by nealoke** [comment]
@ankeetmaini any news on this? :p

**Comment by ankeetmaini** [comment]
@nealoke Sorry, picking this up tonight!

**Comment by nealoke** [comment]
@ankeetmaini looking forward to it ;) 👍

**Comment by ankeetmaini** [comment]
@nealoke do let me know if you like the API in #8

**Comment by kdenz** [comment]
@ankeetmaini Wow looks great! This kind of simplicity really outshines a lot of infinite scroll components out there. Oh what are pullDownToRefreshContent and releaseToRefreshContent for? 

I suggest adding this to https://github.com/enaqx/awesome-react and https://github.com/brillout/awesome-react-components , to get more public exposure after this commit is merged.

**Comment by nealoke** [comment]
@ankeetmaini looking good! :) will try to implement!

**Comment by ankeetmaini** [comment]
@kdenz thank you so so much! Words like this make me feel so happy!

`pullDownToRefreshContent` and `releaseToRefreshContent` can be passed as props as children to show when you pull down. See here the default props https://github.com/ankeetmaini/react-infinite-scroll-component/pull/8/files#diff-2018087f584c4398b5c3a23fc0e5f9dbR168

I just hope I can finish this soon! 😄

**Comment by ankeetmaini** [comment]
@nealoke @kdenz I've released this with minor version. 2.1.0! Cheers :)

**Comment by kdenz** [comment]
@ankeetmaini You're more than welcome! I genuinely think this library deserves a lot more stars. Perhaps having a demo site online hosted on Github pages or Netlify would also help?

**Comment by nealoke** [comment]
@kdenz @ankeetmaini definitely think that a demo page with some simple docs will help! Great effort!
