### ISSUE TITLE
Next function called once only

### ISSUE THREAD

**Issue by DivyamShukla** [ankeetmaini/react-infinite-scroll-component#56]
Please check

**Comment by apoorvtomar2222** [comment]
@DivyamShukla 

In What situation does your next does not work.

A case might be you have set hasMore boolean as false. On subsequent call.

**Comment by karanmartian** [comment]
Hi @ankeetmaini any update on the fix for this. 4.0.2 is breaking on this issue. 3.0.2 works fine

**Comment by ankeetmaini** [comment]
Hi guys, I've updated the examples, and you should use only the lates version i.e. v4.0.3

Please checkout the demo from the readme file https://github.com/ankeetmaini/react-infinite-scroll-component#live-examples.

I'm closing this for now, please reopen if the issue still persists. Sorry for the delay!
