### ISSUE TITLE
Is it possible to use `react-infinite-scroll-component` for scrolling UP?

### ISSUE THREAD

**Issue by olegkalyta** [ankeetmaini/react-infinite-scroll-component#57]
I need to have exactly the same behavior but for scrolling up also. Is it possible using this component?

**Comment by ankeetmaini** [comment]
As of now no. :( The scroll handler only works for scrolling down. I can take this up on a weekend.

**Comment by WilliamStephens** [comment]
@ankeetmaini I would be willing to work on this if you could give me some more information on how you would want it implemented.

**Comment by ankeetmaini** [comment]
@WilliamStephens so I'm thinking like in the [onScrollHandler](https://github.com/ankeetmaini/react-infinite-scroll-component/blob/master/app/index.js#L160) I check if the element is at the bottom, then we call the next prop, similarly we'll check if the element has reached the top and call another prop say `previous`

some cases you might need to consider

- show loader at the top
- the user must prepend the data in the children
- scroll position handling

this is what I can think from the top of my mind.

**Comment by ankeetmaini** [comment]
Right, I don't think `Pull Down` gesture makes sense if the component is
scrolled bidirectionally. So I think it should be safe to turn the `Pull
down` feature off if the user wants bidirectional scroll functionality.

**Comment by WilliamStephens** [comment]
@ankeetmaini Ahh okay I think we are talking about two different features. I was thinking about this as the same functionality just reverse, so it would only scroll up or down not both at the same time. I think bidirectional scroll would take a little bit more time than I have right now. I might just implement a scroll up in a fork if that isn't a feature you want to support

**Comment by VovaCHTB** [comment]
The same issue, need to scroll up.

**Comment by AndrewTkachenko** [comment]
A lot of people need "scroll up" function :) Please, don't ignore it. Thanks

**Comment by hyzhak** [comment]
yeah, it would be very useful feature

**Comment by mimiqkz** [comment]
The bidirectional scroll is great. Any news on it ?

**Comment by wootwoot1234** [comment]
@ankeetmaini  I'm interested in this too. :)

**Comment by gostavee** [comment]
Same here, this component is almost perfect (will be after adding scroll up :D).

**Comment by sulaiman1073** [comment]
Also interested in such a feature.

**Comment by vemundeldegard** [comment]
Need this!

**Comment by CryceTruly** [comment]
need this

**Comment by douglasrcjames** [comment]
Also was looking for this in a library when looking for a chat solution, bumping

**Comment by baeteja** [comment]
Bump

**Comment by Endeauvirr** [comment]
Bump as well - that would be a great feature!

**Comment by roxdavirox** [comment]
I need this :(

**Comment by kpc0511** [comment]
I need this for chat. Any update?

**Comment by jpmayorga** [comment]
HEY! :( We need this update :(

**Comment by aldo1400** [comment]
same here :(

**Comment by LombaxTech** [comment]
I need an upward scroll aswell please.

**Comment by ilitvinovich** [comment]
I'm gonna use another component just because this doesn't have an upward scroll

**Comment by osmarpb97** [comment]
@joserivera12 and I made a pull request with this functionality. pullhttps://github.com/ankeetmaini/react-infinite-scroll-component/pull/207

**Comment by ankeetmaini** [comment]
Wow that's fantastic! I'll check this today!

**Comment by ankeetmaini** [comment]
This feature has landed in the latest version :)

**Comment by roxdavirox** [comment]
I just merged 2 scroll components. hahahaha
