### ISSUE TITLE
Problem with styling

### ISSUE THREAD

**Issue by staho** [ankeetmaini/react-infinite-scroll-component#61]
I've problem with styling when component is in the middle of context. 
```
<div></div>
<div>There I have component</div>
<div></div>
```

And the InfiniteScroll makes a div around him and there is no way to inherit hight from outer component. The only solution which I found is to change line:
From `var outerDivStyle = this.props.pullDownToRefresh && this.props.height ? { overflow: "auto" } : {};`
To: `var outerDivStyle = this.props.pullDownToRefresh && this.props.height ? { overflow: "auto", height: "inherit" } : {};`

![screen shot 2018-05-20 at 14 40 11](https://user-images.githubusercontent.com/17594777/40279011-c4cd61d0-5c3b-11e8-8eda-bb99cf945ab4.png)
As you can see `height:"inherited"` was set in InfiniteScroll props but it inherits from this outerDiv instead of parent.

Also I don't want to specify constant height due to responsiveness of app.

**Comment by ankeetmaini** [comment]
Hi @staho, I am not sure if I completely understand your problem. As far as I can understand you want to style the content, can you do something like this https://codesandbox.io/s/0ykkzx672n

Here I am wrapping the content in my own div and styling it as I want. Does this help? If not can you give me a reproduce-able sample?
```js
<InfiniteScroll
          dataLength={this.state.items.length}
          next={this.fetchMoreData}
          hasMore={true}
          loader={<h4>Loading...</h4>}
        >
          <div style={{ border: "10px solid red" }}>
            {this.state.items.map((i, index) => (
              <div style={style} key={index}>
                div - #{index}
              </div>
            ))}
          </div>
        </InfiniteScroll>
```
