### ISSUE TITLE
scrollableTarget not working

### ISSUE THREAD

**Issue by lsvargas** [ankeetmaini/react-infinite-scroll-component#62]
Hi, i was having trouble while using infinite scrolling, because data was being loaded when my browsers main window scrollbar scrolled. So i tried using scrollableTarget to fix the problem, but when i tried using it the loader keeps displaying and no data is fetched. Code looks like this:
```
<Container id="divID">
        <InfiniteScroll
          dataLength={this.state.logs.length}
          next={this.fetchMoreData}
          hasMore={true}
          loader={<Loader />}
          scrollableTarget="divID"
        >
          <Table striped>
            <thead>
              <tr>
                <th>...</th>
                <th>...</th>
                <th>...</th>
              </tr>
            </thead>
            <tbody>
              {this.state.logs.map(event => (
                <tr key={event.id}>
                  <td>....</td>
                  <td>....</td>
                  <td>....</td>
                </tr>
                    ))}
            </tbody>
          </Table>
        </InfiniteScroll>
</Container>
```
Here you can see the id of Container
![screen shot 2018-05-28 at 00 25 05](https://user-images.githubusercontent.com/11396574/40597185-d3bf85d8-620d-11e8-9bea-dee5c44e7880.png)

I Also tried using `scrollableTarget=document.getElementById("divID")` and it now renders the content but it only loads more data when the main window scrollbar moves not when the one in my Table element does.

**Comment by ankeetmaini** [comment]
When the scrolling is on your main browser's window you don't need scrollableTarget at all. You can just make it working like this https://codesandbox.io/s/yk7637p62z

**Comment by rajivhbk** [comment]
@lsvargas any progress on this issue?

**Comment by ankeetmaini** [comment]
@rajivhbk it won't work with refs because React renders children first and then parent. By the time InfiniteScroll mounts, the parent ref would be null.

To overcome this you can use id on your DOM element. Please see a working example here https://codesandbox.io/s/r7rp40n0zm

**Comment by rajivhbk** [comment]
@ankeetmaini  yes i tried that too . passing id, passing document.getElementById('id')..
didn't work for me. I'm using this component . the body of which has overflow-y: scroll , and height is calculated like :  height: calc(100vh - 4.75rem) ... the body contains other components along with a table component which has a TableRows component placed inside <infiniteScroll> .

**Comment by rajivhbk** [comment]
i passed it down to the div having the scrollbars as a prop from the component. i also tried giving an id directly to the div of the body component. Didn't work. It's a complicated implementation still i'll try to write an example to reproduce this.

**Comment by kumawatanupriya** [comment]
@rajivhbk Did you solve it?  I am also facing the same issue, I am using react infinite scroll.

**Comment by moecantplay** [comment]
i am facing the same issue where scrollableTarget isn't working as expected.

**Comment by aakin03** [comment]
Hi, I know this issue has been closed, but are we still able to get a response?
I'm having a similar issue as many of those previously. I've set up InfinteScroll to wrap around a Table. InfinteScroll & Table are located inside of a TableContainer component. The TableContainer has an id which I used as the `scrollableTarget` in InfinteScroll. In my main page, my table scrolls as expected with more data loading when I pass the threshold. However, when I try to use my table in a Dialog, InfinteScroll no longer works. When I scroll, I'm not reaching my `next` function. How can InfinteScroll work while on a main window, but not when in a Dialog?

**Comment by missingone6** [comment]
Hello, have you solved it yet

**Comment by shurintou** [comment]
@aakin03 Hi, I'm facing same issue just as you mentioned, that scrollableTarget is not working while in a Dialog. (In my case I use Ant design Modal), have you solved this issue yet?

**Comment by osamamammar** [comment]
> @aakin03 Hi, I'm facing same issue just as you mentioned, that scrollableTarget is not working while in a Dialog. (In my case I use Ant design Modal), have you solved this issue yet?

same problem have you solved it I'm using ant design also

**Comment by murilooon** [comment]
Same problem inside an Ant design Drawer component 😞

**Comment by SreenathDev6** [comment]
same issue for me too:
here is my code:
<Grid container spacing={3} id='scrollableDiv' style={{ height: 1000, overflow: 'auto' }}>
        <InfiniteScroll
          dataLength={postData.length}
          next={fetchData}
          inverse={true}
          hasMore={true}
          loader={<h4>Loading...</h4>}
          scrollableTarget='scrollableDiv' // Make sure this matches the ID of the scrollable element
        >
          {isLoading ? (
            <Typography variant='h6'>Loading...</Typography>
          ) : postData ? (
            postData.map(post => (
              <Grid item key={post.id}>
                <Card style={{ margin: '8px' }}>
                  <CardContent>
                    <Typography variant='h6'>{post.title}</Typography>
                    <Typography variant='body2'>{post.body}</Typography>
                  </CardContent>
                </Card>
              </Grid>
            ))
          ) : (
            <Typography variant='h6'>No data available</Typography>
          )}
        </InfiniteScroll>
      </Grid>

**Comment by ma-bt** [comment]
Did anyone solved that issue?

**Comment by thanhtoanDuong** [comment]
I try to move id="scrollableDiv" to component which have style    max-height: 500px; overflow: auto; and it works. The key thing is you must place id="scrollableDiv" in right place
