### ISSUE TITLE
Remove proptypes from production build

### ISSUE THREAD

**Issue by mrchief** [ankeetmaini/react-infinite-scroll-component#63]
Proptypes brings in around 3k baggage. It'd be nice if the component stripped proptypes from production build. See https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types

**Comment by mrchief** [comment]
> But I think this should be done in userland code, in their webpack configs

Ideally yes. But webpacking already webpacked code can lead to issues (not sure it does in this case - I'll know once i give it try). Are you planning to support `package.module` or `package.jsnext:main` which exposes the non webpacked files?

The ideal solution would be to do what react does - expose a dev build and a prod build. It's more work for us library authors though. (I'm currently debating the same for my component - whether to keep proptypes or not, whether to minify or not etc. etc.)

**Comment by ankeetmaini** [comment]
Yes I've been planning to expose jsmain modules. I'll take a look at
react's packaging and try it out! Thanks

**Comment by ankeetmaini** [comment]
#126
