### ISSUE TITLE
use on table 

### ISSUE THREAD

**Issue by alexbigapps23** [ankeetmaini/react-infinite-scroll-component#66]
hi, how I can use this on the table?

**Comment by server-izetov** [comment]
Hi @alexbigapps23 !

You can use as template example from this issue #62

**Comment by nareshbhatia** [comment]
I have a table version buried in here: https://github.com/nareshbhatia/infinite-scroll-demo. You will have to comment out the div version and uncomment the table version in app.js.

**Comment by EJohnF** [comment]
but what's about sticky header?

**Comment by skvlakov** [comment]
Please, can be it used with "table" "position: sticky" ?
