### ISSUE TITLE
I'm using infinite-scroll-component and next is not hitting fetchMoreData

### ISSUE THREAD

**Issue by infinitescrollissue** [ankeetmaini/react-infinite-scroll-component#72]
Next is not hitting fetchMoreData function. It is only hitting once even dataLength is 3. Can you help me with this issue

**Comment by tommyalvarez** [comment]
@infinitescrollissue did you set the prop _more_ as true when fetching the first page of records? It's working for me. I have just implemented it

**Comment by ankeetmaini** [comment]
@infinitescrollissue in the first load of your data, make sure there's a scroll, in case your items are too less to cause a scroll the onScroll listener will not trigger.

**Comment by benistary** [comment]
I have same problem. **next** prop calls fetchMoreData only when the array data has **lenght 3 or more.**

**Comment by lifedup** [comment]
I have the same issue! It's not calling the next function.  If I manually put a scroll listener and call my load more it works.  The issue is with this.  I have hasMore set and it's true, the scrollbar is there on load, 12 items load per call that are about half screen each.  The loader prop shows but never calls next.

**Comment by jgroh9** [comment]
@infinitescrollissue @benistary  I too had this same issue. In my case, the problem was related to the `dataLength` attribute. I had initially set it to the total count of all the records in the collection that I was trying to load, but it had to be set to the current length of the data being displayed.  In the below example I originally had set `dataLength={500}` but this only called `fetchMoreItems()` once. After changing to `dataLength={this.state.items.length}` things started working as expected. 

```
this.state = { items: [], hasMoreItems: true };

fetchMoreItems() {
  if (this.state.items.length >= 500) {
    this.setState({ hasMoreItems: false });
    return;
  }

  // a fake async api call
  setTimeout(() => {
    this.setState({
      items: this.state.items.concat(Array.from({ length: 20 }))
    });
  }, 500);
}

<InfiniteScroll
  dataLength={this.state.items.length}
  next={this.fetchMoreItems}
  hasMore={this.state.hasMoreItems}
>
</InfiniteScroll>
```

Hope this helps

**Comment by nishalk01** [comment]
Thanks that helped a lot

**Comment by Lesleytech** [comment]
> @infinitescrollissue @benistary I too had this same issue. In my case, the problem was related to the `dataLength` attribute. I had initially set it to the total count of all the records in the collection that I was trying to load, but it had to be set to the current length of the data being displayed. In the below example I originally had set `dataLength={500}` but this only called `fetchMoreItems()` once. After changing to `dataLength={this.state.items.length}` things started working as expected.
> 
> ```
> this.state = { items: [], hasMoreItems: true };
> 
> fetchMoreItems() {
>   if (this.state.items.length >= 500) {
>     this.setState({ hasMoreItems: false });
>     return;
>   }
> 
>   // a fake async api call
>   setTimeout(() => {
>     this.setState({
>       items: this.state.items.concat(Array.from({ length: 20 }))
>     });
>   }, 500);
> }
> 
> <InfiniteScroll
>   dataLength={this.state.items.length}
>   next={this.fetchMoreItems}
>   hasMore={this.state.hasMoreItems}
> >
> </InfiniteScroll>
> ```
> 
> Hope this helps

Thanks a million. This solved the problem

**Comment by nilesh-jagtap-patona** [comment]
> > @infinitescrollissue @benistary I too had this same issue. In my case, the problem was related to the `dataLength` attribute. I had initially set it to the total count of all the records in the collection that I was trying to load, but it had to be set to the current length of the data being displayed. In the below example I originally had set `dataLength={500}` but this only called `fetchMoreItems()` once. After changing to `dataLength={this.state.items.length}` things started working as expected.
> > ```
> > this.state = { items: [], hasMoreItems: true };
> > 
> > fetchMoreItems() {
> >   if (this.state.items.length >= 500) {
> >     this.setState({ hasMoreItems: false });
> >     return;
> >   }
> > 
> >   // a fake async api call
> >   setTimeout(() => {
> >     this.setState({
> >       items: this.state.items.concat(Array.from({ length: 20 }))
> >     });
> >   }, 500);
> > }
> > 
> > <InfiniteScroll
> >   dataLength={this.state.items.length}
> >   next={this.fetchMoreItems}
> >   hasMore={this.state.hasMoreItems}
> > >
> > </InfiniteScroll>
> > ```
> > 
> > 
> > Hope this helps
> 
> Thanks a million. This solved the problem

----------------------

Thats awesome, helped me a lot, this was the exact mistake I was doing ... Thanks a ton man

**Comment by mertyldrr** [comment]
Thanks a lot, I was trying to understand where the problem is. A bit more explanatory text for dataLength would be good. It is hard to understand if it's total length of data or currently displayed data length (at least for me).

**Comment by CSEKU160212** [comment]
The next function is not calling:  Help me!
Code is: 

![Untitled (1)](https://user-images.githubusercontent.com/23745270/160166479-29e6ae84-9a89-49a1-8679-c9d385b3cbf6.jpeg)

and PropsData are: 

![Capture](https://user-images.githubusercontent.com/23745270/160166531-e4fabcc1-9300-44b9-832c-d11cd1cc78f8.JPG)

**Comment by GokulSuresh27** [comment]
> @infinitescrollissue @benistary I too had this same issue. In my case, the problem was related to the `dataLength` attribute. I had initially set it to the total count of all the records in the collection that I was trying to load, but it had to be set to the current length of the data being displayed. In the below example I originally had set `dataLength={500}` but this only called `fetchMoreItems()` once. After changing to `dataLength={this.state.items.length}` things started working as expected.
> 
> ```
> this.state = { items: [], hasMoreItems: true };
> 
> fetchMoreItems() {
>   if (this.state.items.length >= 500) {
>     this.setState({ hasMoreItems: false });
>     return;
>   }
> 
>   // a fake async api call
>   setTimeout(() => {
>     this.setState({
>       items: this.state.items.concat(Array.from({ length: 20 }))
>     });
>   }, 500);
> }
> 
> <InfiniteScroll
>   dataLength={this.state.items.length}
>   next={this.fetchMoreItems}
>   hasMore={this.state.hasMoreItems}
> >
> </InfiniteScroll>
> ```
> 
> Hope this helps

Thanks a lott Man.
