### ISSUE TITLE
Keep scroll on same position

### ISSUE THREAD

**Issue by Fed0t** [ankeetmaini/react-infinite-scroll-component#74]
Hello,

How to keep the scroll in same position when i unshift and render new item in list( this.renderConversations() in this function i have a loop on redux state list) ? 

If i update existing item in the list the scroll keep same position.Only when i add new item in list scroll loose position.Thank you!
`

> <InfiniteScroll
                        dataLength={conversations.list.length}
                        next={() => this.props.fetchMoreUnreadedConversations(conversations.next_page_url)}
                        hasMore={(conversations.next_page_url)}
                        height={440}
                        useWindow={false}
                        loader={<h4 className="text-center">Loading...</h4>}
                        pullDownToRefresh
                        pullDownToRefreshContent={
                            <h3 style={{textAlign: 'center', color: '#FFF'}}>&#8595; Pull down to refresh</h3>
                        }
                        releaseToRefreshContent={
                            <h3 style={{textAlign: 'center', color: '#FFF'}}>&#8593; Release to refresh</h3>
                        }
                        refreshFunction={() => {
                            console.log('refresh')
                        }}>
                        {this.renderConversations()}
                    </InfiniteScroll>

`

**Comment by Fed0t** [comment]
i used refs and state :) thank you!

**Comment by kiloki-official** [comment]
That's not a solution,
