### ISSUE TITLE
Edge Scrolling issue

### ISSUE THREAD

**Issue by Mujaddadi** [ankeetmaini/react-infinite-scroll-component#76]
It seems to me that without adding the height prop, the scrolling is not working in edge. It even worked in IE. Can anyone confirm it?

**Comment by satejrajam30** [comment]
Even I am facing same problem, any solution to this?

**Comment by Mujaddadi** [comment]
Just add `height={window.innerHeight * 0.9}` to make everyone happy.

**Comment by satejrajam30** [comment]
@Mujaddadi Thank you, I will give it a try
