### ISSUE TITLE
Cannot find module './factoryWithTypeCheckers'

### ISSUE THREAD

**Issue by davidcastrojobsity** [ankeetmaini/react-infinite-scroll-component#77]
I'm getting this error when compiling:
`Error: Cannot find module './factoryWithTypeCheckers' from '.../node_modules/react-infinite-scroll-component/lib'`

I'm using react 16.6

Any help is appreciated

**Comment by ankeetmaini** [comment]
Hi this isn't currently tested with the latest version of react. I'll try
and see it working on a day or two.

**Comment by davidcastrojobsity** [comment]
Hello @ankeetmaini, thanks for your response, have you had the time to check this issue?

**Comment by ankeetmaini** [comment]
Hi, I just tested it with the latest version of react 16.6. I didn;t get any error. https://codesandbox.io/s/4349rqm3kx

Also, could you delete your node_modules and do npm i freshly? This maybe due to `prop-types` module is missing.
