### ISSUE TITLE
Remove Throttle Effect

### ISSUE THREAD

**Issue by satejrajam30** [ankeetmaini/react-infinite-scroll-component#78]
Is there a way to remove throttle? When we scroll fast the events are not captured & results in lagging behavior.

**Comment by echeong09** [comment]
We're currently experiencing this issue as well. Have you looked into a workaround for this? @satejrajam30

**Comment by satejrajam30** [comment]
@echeong09 : setting the min-height to 100% for the parent container, solved the issue for me.

**Comment by echeong09** [comment]
@satejrajam30 Awesome, thanks for this!
