### ISSUE TITLE
Adding Support to `className` 

### ISSUE THREAD

**Issue by TheBearSO** [ankeetmaini/react-infinite-scroll-component#81]
**"react-infinite-scroll-component": "^4.2.0"**

Hi, I'm using this lib, it worked really well. 

One thing that I've tried to do without success is put an additional class to InfiniteScroll rendered wrap element. In my case I'm rendering bootstrap cols and I want to add a row as immediate parent div. 

```
<InfiniteScroll
            className="row custom-class" //this is what I've tried and none class were added
            dataLength={this.vm.items.length} 
            next={this.loadFunc}
            hasMore={this.vm.filter.hasNextPage}>
```
To fix it, I had to manually add the following css to simulate the bootstrap row:

```
    .infinite-scroll-component{
        display: flex;
        flex-wrap: wrap;
        margin-right: -15px;
        margin-left: -15px;
    }
```

I think could be really simple to support this scenario, if make sense I could help to do it.

Maybe change this line https://github.com/ankeetmaini/react-infinite-scroll-component/blob/master/app/index.js#L226
to: `className={`infinite-scroll-component ${this.props.className || ''}`}`

Regards

**Comment by ankeetmaini** [comment]
@TheBearSO can you submit a PR? :)

Sorry for not getting to it earlier!

**Comment by TheBearSO** [comment]
Hi @ankeetmaini I've already done it... https://github.com/ankeetmaini/react-infinite-scroll-component/pull/82

**Comment by Kostanos** [comment]
I guess this issue could be closed already no?
