### ISSUE TITLE
Support custom wrapping component for outerDiv

### ISSUE THREAD

**Issue by alexanderjeurissen** [ankeetmaini/react-infinite-scroll-component#84]
It would be great if instead of always rendering an outer `<div>` that the user can specify what `tag` to render. This is especially useful if the InfiniteScrollComponent is rendered inside a table for instance. Something similar to what the `Fade` component of `ReactStrap` supports would suffice:

https://github.com/reactstrap/reactstrap/blob/master/src/Fade.js

relevant code snippet:

```
function Fade(props) {
  const {
    tag: Tag,
    baseClass,
    baseClassActive,
    className,
    cssModule,
    children,
    innerRef,
    ...otherProps
  } = props;

  const transitionProps = pick(otherProps, TransitionPropTypeKeys);
  const childProps = omit(otherProps, TransitionPropTypeKeys);

  return (
    <Transition {...transitionProps}>
      {(status) => {
        const isActive = status === 'entered';
        const classes = mapToCssModules(classNames(
          className,
          baseClass,
          isActive && baseClassActive
        ), cssModule);
        return (
          <Tag className={classes} {...childProps} ref={innerRef}>
            {children}
          </Tag>
        );
      }}
    </Transition>
  );
}
```

in other words this would be as simple as:

1. Allow passing `tag` prop
2. Add default prop so that `tag` is a `div` by default.

**Comment by ankeetmaini** [comment]
So will tag be just a Dom node or it can be a component too?

I'm not sure if it'll be seamless because I depend on some styling i.e
overflow on the div. But I'm curious to know the usecase for this!

**Comment by ankeetmaini** [comment]
Outer div now has a className which you can target. Thanks

**Comment by franciscohanna92** [comment]
I think the className support fix doesn't addresses this ticket. 

The use case for rendering other element than `div` for the wrapper can be observed in tables. If you try the following structure:

```javascript
<table>
  <thead>
    {/* render your headers */}
  </thead>
  <tbody>
    <InfiniteScroll
      dataLength={this.state.rows.length}
      next={this.loadMoreRows}
      hasMore={this.state.hasMoreRows}>
      {
        this.state.rows.map(row => (
          {/* render your rows */}
        ))
      }
    </InfiniteScroll>
  </tbody>
</table>
```

The following warning appears on the console:
```
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <div>.
```

Which makes sense, because you are basically violating the HTML spec for tables. 

A better approch will be to allow the wrapper component to be any element that you want, specifiyng an `as` prop of type `string` or `React.Node`, defaulting to `div`, like so:

```javascript
<table>
  <thead>
    {/* render your renders */}
  </thead>
  <InfiniteScroll
    dataLength={this.state.rows.length}
    next={this.loadMoreRows}
    as='tbody'
    hasMore={this.state.hasMoreRows}>
    {
      this.state.rows.map(row => (
        {/* render your rows */}
      ))
    }
  </InfiniteScroll>
</table>
```

What dou you think @ankeetmaini ?

**Comment by fourbytes** [comment]
:+1: Just come across this issue too, being able to use tbody as the element type would be great.

**Comment by pouriamoosavi** [comment]
Hi any news about this?

**Comment by guaycuru** [comment]
Could we please reopen this?
