### ISSUE TITLE
refresh function missing

### ISSUE THREAD

**Issue by The-Code-Monkey** [ankeetmaini/react-infinite-scroll-component#85]
so i get this error but i have a refresh function there as its the same function that loads the original data.

Error: Mandatory prop "refreshFunction" missing.
          Pull Down To Refresh functionality will not work
          as expected. Check README.md for usage'

    <InfiniteScroll
       dataLength={this.props.posts.length}
       next={() => this.props.dispatch(nextPage())}
       loader={<h4>Loading...</h4>}
       refreshFunction={this.refresh()}
       endMessage={
          <p style={{textAlign: 'center'}}>
             <b>Yay! You have seen it all</b>
          </p>
       }
       pullDownToRefresh
       pullDownToRefreshContent={
           <h3 style={{textAlign: 'center'}}>&#8595; Pull down to refresh</h3>
       }
       releaseToRefreshContent={
          <h3 style={{textAlign: 'center'}}>&#8593; Release to refresh</h3>
       }
    >

and then my function is 

    this.props.dispatch(getFeed()) 

why won't it recognise that function

**Comment by ankeetmaini** [comment]
Hi, you're calling the refresh function in the prop.

```jsx
<InfiniteScroll
  refresh={this.refresh}
>
</InfiniteScroll>
```

Also, see this example https://codesandbox.io/s/jz45k82973

Please re-open if you've any other issues.

**Comment by mwalol** [comment]
i confirm it doesn't work with this current version 5.0.4
