### ISSUE TITLE
Refresh from button problem with Y scroll

### ISSUE THREAD

**Issue by richardpramono** [ankeetmaini/react-infinite-scroll-component#86]
How to Refresh scroll data from buttons?

I managed to create my own refresh function inside a refresh button, but when refresh function is called, the Y scroll position still in the middle (stays where it was), and because it's in the middle, it will trigger another several new fetch request. How do I set the Y scroll position to top, before I refresh the data?

Thank you

**Comment by ankeetmaini** [comment]
https://codesandbox.io/s/qlkxmwoojj

Check the above sample, `refresh` function is nothing but a function that sends new props. As your main data prop changes `dataLength` prop will automatically re-render the InfiniteScroll function

**Comment by ankeetmaini** [comment]
I am closing this for now, but please feel free to re-open if things don't work out.
