### ISSUE TITLE
Infinite-scroll example no height version doesn't work on 4k monitor~

### ISSUE THREAD

**Issue by kdenz** [ankeetmaini/react-infinite-scroll-component#9]
![image](https://cloud.githubusercontent.com/assets/12795428/23311302/92db591e-faf0-11e6-9a53-58fad3b10b99.png)

There're not enough elements for the scrolling to be workable~

**Comment by ankeetmaini** [comment]
Oops!

**Comment by ankeetmaini** [comment]
Fixed! Thanks again @kdenz :)
